accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "accounts"

urlpatterns = [
    path('register',views.user_registration, name="register"),
    path('login',auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path('logout',auth_views.LogoutView.as_view(template_name="accounts/logout.html"), name="logout"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),

    # for user authentication
    path('accounts/', include("accounts.urls"), name='accounts'),

    # for blogs related urls
    path('', include("blogs.urls"), name='blog'),

    # for blogs related urls
    path('', include("products.urls"), name='products'),

    # for frontend related urls
    path('', include("frontend.urls"), name='frontend'),

    # for ckeditor
    path('ckeditor/', include('ckeditor_uploader.urls')),

]

urlpatterns += [
    re_path(r'^(?:.*)$', TemplateView.as_view(template_name='frontend/index.html')),
]

frontend/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name = 'frontend'

from .views import (
    index
)

urlpatterns = [

    # for index page
    path('', index, name="index"),

    path('', TemplateView.as_view(template_name="frontend/index.html"), name='frontend'),
]

products/urls.py
from django.urls import path

from .views import (
    ItemListAPI,
    ItemDetailAPI,
    CategoryAPI,
    CartToggleAPI,
    user_cart,
    remove_from_cart,
    order_items,
    payment_success,
)

app_name = 'products'

urlpatterns = [

    # for fetching items
    path('api/items/', ItemListAPI.as_view(), name='items'),
    path('api/item/<str:title_slug>', ItemDetailAPI.as_view(), name='item-detail'),

    # for fetching catogory
    path('api/category', CategoryAPI.as_view(), name='category'),

    # for add/removing item from cart
    path('api/cart', CartToggleAPI.as_view(), name='cart'),
    path('remove/<str:slug>', remove_from_cart, name='remove-item'),

    path('my-cart', user_cart, name='my-cart'),
    path('order', order_items, name='order'),
    path('payment-complete', payment_success, name='payment-complete'),

]

templates/layouts/footer.html
<footer class="footer">
    <div class="footer-area">
        <div class="container">
            <div class="row section_gap">
                <div class="col-lg-5 col-md-6 col-sm-6">
                    <div class="single-footer-widget tp_widgets">
                        <h4 class="footer_title large_title">Our Mission</h4>
                        <p>
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa fuga est aliquam quasi
                            dolorem tempora consequatur! Dolorem mollitia voluptas est corrupti ipsa necessitatibus
                            tempore quisquam iusto neque, corporis, commodi esse.
                        </p>
                    </div>
                </div>
                <div class="offset-lg-1 col-lg-2 col-md-6 col-sm-6">
                    <div class="single-footer-widget tp_widgets">
                        <h4 class="footer_title">Quick Links</h4>
                        <ul class="list">
                            <li><a href="{% url 'frontend:index' %}">Home</a></li>
                            <li><a href="{% url 'frontend:frontend' %}items">Shop</a></li>
                            <li><a href="{% url 'frontend:frontend' %}blogs">Blog</a></li>
                        </ul>
                    </div>
                </div>
                <div class="offset-lg-1 col-lg-3 col-md-6 col-sm-6">
                    <div class="single-footer-widget tp_widgets">
                        <h4 class="footer_title">Contact Us</h4>
                        <div class="ml-40">
                            <p class="sm-head">
                                <span class="fa fa-location-arrow"></span>
                                Head Office
                            </p>
                            <p>123, Main Street, Your City</p>

                            <p class="sm-head">
                                <span class="fa fa-phone"></span>
                                Phone Number
                            </p>
                            <p>
                                +123 456 7890 <br>
                                +123 456 7890
                            </p>

                            <p class="sm-head">
                                <span class="fa fa-envelope"></span>
                                Email
                            </p>
                            <p>
                                free@infoexample.com <br>
                                www.infoexample.com
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/layouts/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>E-commerce</title>
    <link rel="icon" href="img/Fevicon.png" type="image/png">

    <!-- linking css -->

    <!-- bootstrap -->
    <link rel="stylesheet" href="{% static 'vendors/bootstrap/bootstrap.min.css' %}">

    <!-- themify icon -->
    <link rel="stylesheet" href="{% static 'vendors/themify-icons/themify-icons.css' %}">

    <!-- sweetalert2 -->
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/11.0.20/sweetalert2.min.css" />

    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body>

    {% include 'layouts/navbar.html' %}

    {% block body %}{% endblock body %}

    {% include 'layouts/footer.html' %}


    <!-- linking js -->

    <!-- jquery -->
    <script src="{% static 'vendors/jquery/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'vendors/jquery.ajaxchimp.min.js' %}"></script>

    <!-- bootstrap -->
    <script src="{% static 'vendors/bootstrap/bootstrap.bundle.min.js' %}"></script>

    <!-- axios -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js"></script>

    <!-- sweetalert2 -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/11.0.20/sweetalert2.min.js"></script>

    <!-- custom  -->
    <script>
        const cartActiveUrl = "{% url 'products:cart' %}"
    </script>
    <script src="{% static 'js/app.js' %}"></script>

    {% block js %}{% endblock js %}
</body>

</html>

templates/layouts/navbar.html
{% load static %}
<header class="header_area">
    <div class="main_menu">
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="container">
                <a class="navbar-brand logo_h" href="{% url 'frontend:index' %}">
                    <h2>E-commerce</h2>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                    <ul class="nav navbar-nav menu_nav ml-auto mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'frontend:index' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'frontend:frontend' %}items">Shop</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'frontend:frontend' %}blogs">Blogs</a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                        </li>
                        {% endif %}

                    </ul>

                    <ul class="nav-shop">
                        <li class="nav-item">
                            <a href="{% url 'products:my-cart' %}" class="nav-link">
                                <button>
                                    <i class="ti-shopping-cart"></i>
                                </button>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="button button-header" href="{% url 'frontend:frontend' %}items">Buy Now</a>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>
    </div>
</header>