core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),

    # for user authentication
    path('accounts/', include("accounts.urls"), name='accounts'),

    # for blogs related urls
    path('', include("blogs.urls"), name='blog'),

    # for blogs related urls
    path('', include("products.urls"), name='products'),

    # for frontend related urls
    path('', include("frontend.urls"), name='frontend'),

    # for ckeditor
    path('ckeditor/', include('ckeditor_uploader.urls')),

]

urlpatterns += [
    re_path(r'^(?:.*)$', TemplateView.as_view(template_name='frontend/index.html')),
]

frontend/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name = 'frontend'

from .views import (
    index
)

urlpatterns = [

    # for index page
    path('', index, name="index"),

    path('', TemplateView.as_view(template_name="frontend/index.html"), name='frontend'),
]

products/urls.py
from django.urls import path

from .views import (
    ItemListAPI,
    ItemDetailAPI,
    CategoryAPI,
    CartToggleAPI,
    user_cart,
    remove_from_cart,
    order_items,
    payment_success,
)

app_name = 'products'

urlpatterns = [

    # for fetching items
    path('api/items/', ItemListAPI.as_view(), name='items'),
    path('api/item/<str:title_slug>', ItemDetailAPI.as_view(), name='item-detail'),

    # for fetching catogory
    path('api/category', CategoryAPI.as_view(), name='category'),

    # for add/removing item from cart
    path('api/cart', CartToggleAPI.as_view(), name='cart'),
    path('remove/<str:slug>', remove_from_cart, name='remove-item'),

    path('my-cart', user_cart, name='my-cart'),
    path('order', order_items, name='order'),
    path('payment-complete', payment_success, name='payment-complete'),

]

products/models.py
from datetime import date

from django.db import models
from django.db.models import Q
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify


# django image kit model
# https://pypi.org/project/django-imagekit/
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import Resize


class Category(models.Model):
    ct = models.CharField(max_length=255)

    def __str__(self):
        return self.ct


class Item(models.Model):

    class Meta:
        ordering = ("-date_added",)

    status_choice = (
        ('D', 'Draft'),
        ('F', 'Featured'),
        ('IS', 'In Stock'),
        ('NA', 'Not Available'),
        ('OS', 'Out Of Stock'),
    )

    title = models.CharField(max_length=255)
    content = models.TextField(max_length=2048)

    price = models.IntegerField()

    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True)
    status = models.CharField(max_length=2, choices=status_choice)
    date_added = models.DateField(auto_now=True)

    title_slug = models.CharField(max_length=350)

    class get_published_items(models.Manager):
        def get_queryset(self):
            return super().get_queryset().filter(~Q(status='D'))

    class get_featured_product(models.Manager):
        def get_queryset(self):
            return super().get_queryset().filter(Q(status='F'))

    objects = models.Manager()
    get_published_items = get_published_items()
    get_featured_product = get_featured_product()

    def save(self, *args, **kwargs):
        if self.date_added:
            today = self.date_added
        else:
            today = date.today()

        self.title_slug = slugify(self.title) + '-' + today.strftime("%d-%b-%Y")
        super(Item, self).save(*args, **kwargs)

    def get_first_thumbnail_img(self):
        img = ItemImage.objects.filter(item=self)
        if img.exists():
            return img.first().image_small
        else:
            return None

    def get_product_image(self):
        img = ItemImage.objects.filter(item=self).distinct()
        return img

    def __str__(self):
        return self.title


class ItemImage(models.Model):
    class Meta:
        verbose_name = 'Item image'
        verbose_name_plural = 'Item images'

    image = ProcessedImageField(upload_to="items", processors=[Resize(550, 550)], format="JPEG")
    image_small = ImageSpecField(source="image", processors=[Resize(200, 200)], format="JPEG")

    item = models.ForeignKey('Item', related_name='item_img', on_delete=models.CASCADE)


class Cart(models.Model):
    user = models.ForeignKey(User, related_name='user_cart', on_delete=models.CASCADE)
    item = models.ForeignKey('Item', related_name='cart_item', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)


    def item_total(self):
        return self.item.price * self.quantity

    def __str__(self):
        return f"{self.item} - {self.quantity}"


class OrderItem(models.Model):
    user = models.ForeignKey(User, related_name="user_orderitem", on_delete=models.CASCADE)
    item = models.ForeignKey('Item', related_name='order_item', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    order = models.ForeignKey('Order', related_name='order', on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user} - added {self.item.title} in their order."


class Order(models.Model):

    order_status = (
        ('P', 'Processing'),
        ('A', 'Accepted'),
        ('D', 'Delivered'),
        ('F', 'Finished'),
    )

    order_id = models.CharField(default="" , max_length=350)
    user = models.ForeignKey(User, related_name="user_order", on_delete=models.CASCADE)
    status = models.CharField(choices=order_status, max_length=1, default='P')
    created_date = models.DateField(auto_now=True)

    total_price = models.IntegerField(default=10000)

    def save(self, *args, **kwargs):
        qs = OrderItem.objects.filter(
            order=self,
            ordered=False
        ).distinct()
        if qs.exists():
            total_price = sum([item.item.price * item.quantity for item in qs])
            self.total_price = total_price
        super(Order, self).save(*args, **kwargs)

products/views.py
import razorpay

# django imports
from django.db.models import Q
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, reverse, HttpResponse

# rest_framework imports
from rest_framework import generics
from rest_framework.views import APIView

from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.status import (
    HTTP_201_CREATED,
    HTTP_404_NOT_FOUND,
    HTTP_202_ACCEPTED,
)

from rest_framework.filters import (
    SearchFilter,
    OrderingFilter,
)

# importing serializers
from .serializers import (
    ItemListSerializer,
    ItemDetailSerializer,
    CategoryListSerializer,
    CartSerializer,
)

# importing model
from .models import (
    Item,
    Category,
    Cart,
    OrderItem,
    Order,
)


class ItemListAPI(generics.ListAPIView):
    queryset = Item.get_published_items.all()
    serializer_class = ItemListSerializer
    filter_backends = [SearchFilter, OrderingFilter]
    search_fields = [
        'title',
        'category__ct',
    ]
    ordering_fields = [
        'price',
    ]

    def get_queryset(self):
        q = self.request.GET.get("ct_filter")
        if q:
            return Item.get_published_items.filter(category__ct=q)
        return Item.get_published_items.all()


class ItemDetailAPI(generics.RetrieveAPIView):
    queryset = Item.get_published_items.all()
    serializer_class = ItemDetailSerializer
    lookup_field = "title_slug"


class CategoryAPI(generics.ListAPIView):
    queryset = Category.objects.all()
    serializer_class = CategoryListSerializer
    pagination_class = None


class CartToggleAPI(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request, format=None):

        slug = request.data.get("slug")
        quantity = request.data.get("quantity", 1)
        print(quantity)

        try:
            item = Item.objects.get(title_slug=slug)
        except Item.DoesNotExist:
            return Response({
                "message": "No such item exist.",
            }, status=HTTP_404_NOT_FOUND)
        cart, created = Cart.objects.get_or_create(
            user=request.user,
            item=item,
        )
        cart.quantity = quantity
        cart.save()
        return Response({
            "message": f"{item.title} has been added to your cart!"
        }, status=HTTP_202_ACCEPTED)

@login_required(login_url="accounts:login")
def user_cart(request):
    qs = Cart.objects.filter(user=request.user).distinct()
    total_price = sum([item.item.price * item.quantity for item in qs])

    return render(request, "products/user-cart.html", {
        "qs": qs,
        "total_price": total_price,
    })


@login_required(login_url="accounts:login")
def remove_from_cart(request, slug):
    item = get_object_or_404(Item, title_slug=slug)
    cart_qs = Cart.objects.filter(user=request.user).distinct()

    for cart_item in cart_qs.all():
        if cart_item.item == item:
            cart_item.delete()

    return HttpResponseRedirect(reverse("products:my-cart"))


@login_required(login_url="accounts:login")
def order_items(request):
    if request.method == "POST":
        user = request.user

        # creating order to add in orderitem
        order = Order.objects.create(user=user)
        # getting all the items from cart
        cart_qs = Cart.objects.filter(user=user).all()

        for cart_item in cart_qs:
            order_item = OrderItem.objects.create(
                user=user,
                item=cart_item.item,
                quantity=cart_item.quantity,
                order=order,
            )
        order.save()  # saving order so that it calculate total price

        rz_key = settings.RAZORPAY_KEY
        _srz_key = settings.RAZORPAY_SECURE_KEY
        
        client = razorpay.Client(auth=(rz_key, _srz_key))
        response = client.order.create({
            "amount": order.total_price*100,
            "currency": "INR",
        })
        order.order_id = response['id']
        order.save()
        return render(request, "products/checkout.html", {
            "order": order,
            "response": response,
        })


@csrf_exempt
def payment_success(request):
    if request.method == "POST":
        order_id = request.POST.get("razorpay_order_id")
        order = Order.objects.get(order_id=order_id)
        order.status = 'A'
        order.save()

        for order_item in order.order.all():
            order_item.ordered = True
            order_item.save()

        return render(request, "products/success.html", {
            "qs": order,
        })

products/templates/products/checkout.html
{% extends 'layouts/layout.html' %}


{% block body %}
    <div class="container my-5">
        <div class="row">
            <div class="col-lg-4 ml-auto">
                <div class="order_box">
                    <h2>Your Order</h2>
                    <ul class="list">
                        <li>
                            <a href="#">
                                <h4>Product <span>Total</span></h4>
                            </a>
                        </li>
                        {% for order in order.order.all %}
                        <li>
                            {{ order.item.title }}
                            <span class="middle">x {{ order.quantity }}</span>
                            <span class="last">${{ order.item.price }}</span>
                        </li>
                        {% endfor %}
                    </ul>
                    <ul class="list list_2">
                        <li><a href="#">Total <span>${{ order.total_price }}</span></a></li>
                    </ul>
                    <div class="text-center">
                        <button class="button button-paypal" type="button" id="rzp-pay-btn">Proceed to RazorPay</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}


{% block js %}
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>

<script>
    var options = {
        "amount": "{{ response.amount }}", // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
        "currency": "{{ response.currency }}",
        "name": "Dakshesh",
        "description": "Complete Your Payment",
        "order_id": "{{ response.id }}",
        "callback_url": "{% url 'products:payment-complete' %}",
        "notes": {
            "address": "Razorpay Corporate Office"
        },
        "theme": {
            "color": "#3399cc"
        }
    };
    var rzp1 = new Razorpay(options);
    document.getElementById('rzp-pay-btn').onclick = function (e) {
        rzp1.open();
        e.preventDefault();
    }
</script>
{% endblock js %}

products/templates/products/success.html
{% extends 'layouts/layout.html' %}


{% block body %}
<div class="container mt-5">
    <div class="row">
        <div class="col-12">
            <h2>Your order is completed</h2>
        </div>
        <div class="col-12">
            <table class="table border">
                <thead>
                    <tr>
                        <th scope="col">Product</th>
                        <th scope="col">Price</th>
                        <th scope="col">Quantity</th>
                    </tr>
                </thead>
                <tbody>

                    {% for x in qs.order.all %}
                    <tr>
                        <th>
                            <p>{{ x.item.title }}</p>
                        </th>
                        <td>
                            <p>{{ x.item.price }}</p>
                        </td>
                        <td>
                            <p>{{ x.quantity }}</p>
                        </td>
                    </tr>
                    {% endfor %}

                    <tr>
                        <td colspan="2">Subtotal</td>
                        <td>
                            <p>{{ qs.total_price }}</p>
                        </td>
                    </tr>

                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock body %}

products/templates/products/user-cart.html
{% extends 'layouts/layout.html' %}


{% block body %}
<!--================Cart Area =================-->
<section class="cart_area">
    <div class="container">
        <div class="cart_inner">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Product</th>
                            <th scope="col">Price</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Total</th>
                        </tr>
                    </thead>
                    <tbody>

                        
                        {% if qs %}
                            
                        {% for cart_item in qs %}
                        <tr>
                            <td>
                                <div class="media">
                                    <div class="d-flex">
                                        <img src="{{ cart_item.item.get_first_thumbnail_img.url }}" alt="">
                                    </div>
                                    <div class="media-body d-flex align-items-center justify-content-between">
                                        <a href="{% url 'frontend:frontend' %}item/{{ cart_item.item.title_slug }}"
                                            class="text-dark">
                                            <p>{{ cart_item.item.title }}</p>
                                        </a>
                                        <a href="{% url 'products:remove-item' cart_item.item.title_slug %}">
                                            <i class="ti-close ml-3 text-danger"></i>
                                        </a>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <h5>${{ cart_item.item.price }}</h5>
                            </td>
                            <td>
                                <div class="product_count">
                                    <p>
                                        {{ cart_item.quantity }}
                                    </p>
                                </div>
                            </td>
                            <td>
                                <h5>${{ cart_item.item_total }}</h5>
                            </td>
                        </tr>
                        {% endfor %}

                        {% else %}

                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td>No item in your cart</td>
                        </tr>

                        {% endif %}
                            

                        <tr>
                            <td></td>
                            <td></td>
                            <td>
                                <h5>Subtotal</h5>
                            </td>
                            <td>
                                <h5>${{ total_price }}</h5>
                            </td>
                        </tr>
                        <tr class="out_button_area">
                            <td class="d-none-l"></td>
                            <td class=""></td>
                            <td></td>
                            <td>
                                <div class="checkout_btn_inner d-flex align-items-center">
                                    <a class="gray_btn" href="{% url 'frontend:frontend' %}items">Continue Shopping</a>
                                    <form action="{% url 'products:order' %}" method="POST">
                                        {% csrf_token %}
                                        <button type="submit" class="primary-btn border-0 ml-2">Proceed to checkout</button>
                                    </form>
                                </div>
                            </td>
                        </tr>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
<!--================End Cart Area =================-->
{% endblock body %}